version: "3"
services:
  burrow:
    build: .
    volumes:
      - ${PWD}/docker-config:/etc/burrow/
      - ${PWD}/tmp:/var/tmp/burrow
    ports:
      - 8008:8000
    networks:
      - proxy_nw

  burrow-dashboard:
    image: "joway/burrow-dashboard:latest"
    ports: 
      - 8095:80
    environment:  
      - BURROW_BACKEND=http://burrow:8000
    depends_on:
      - burrow
    networks:
      - proxy_nw

networks:
  proxy_nw:
    external: true
